[package]
name = "whiteye"
version = "0.1.0"
authors = ["kn-shimada <xianrendaotian012@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.25"
anyhow = "1.0.40"